### ISSUE TITLE
sources/web won't compile with TypeScript 1.6

### ISSUE THREAD

**Issue by vlasenkoalexey** [googledatalab/datalab#583]
Starting from typescript 1.6 Module bodies are parsed in strict mode: https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes#module-bodies-are-parsed-in-strict-mode

When compiled it gives following errors:
datalab/jupyter.ts(88,29): error TS1121: Octal literals are not allowed in strict mode.
datalab/server.ts(27,8): error TS1214: Identifier expected. 'static' is a reserved word in strict mode. Modules are automatically in strict mode.
failed

**Comment by yebrahim** [comment]
Closing as obsolete.
